language: c

os:
  - linux

branches:
  only:
    - unit-tests

git:
  depth: 3

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env:
        - COMPILER=gcc-4.9
        - CONFIG=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env:
        - COMPILER=gcc-5
        - CONFIG=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env:
        - COMPILER=gcc-6
        - CONFIG=Release


before_install:
  - echo $PATH
  - if [ $TRAVIS_OS_NAME == linux ]; then . scripts/ci/before_install.sh; fi
  - echo $CC
  - echo "${CC} --version"
  - echo $COMPILER
  - echo "${COMPILER} --version"
  - which $CC
  - which $COMPILER
  - echo $PATH

install:
  - mkdir build && cd build
  - echo $CONFIG
  - if [ "${CONFIG}" = "Debug" ]; then
        cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_C_COMPILER=$COMPILER -DENABLE_TESTS=YES -DPERFORM_IO=NO -DIO_STATS=NO -DUSE_MPI=NO -DUSE_OPENMP=NO -DUSE_OPENACC=NO -DUSE_CUDA_KERNELS=NO ..
        ;
        make
        ;
    else
        cmake -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_C_COMPILER=$COMPILER -DENABLE_TESTS=YES -DPERFORM_IO=NO -DIO_STATS=NO -DUSE_MPI=NO -DUSE_OPENMP=YES -DUSE_OPENACC=NO -DUSE_CUDA_KERNELS=NO ..
        ;
        make
        ;
    fi
  - cd -

before_script:
  - export OMP_NUM_THREADS=4

script:
  - . scripts/ci/run_tests.sh

after_success:
  - echo "Yess"

after_failure:
  - echo "Noooooooooooo <darth vader voice>"
