language: c

compiler:
  - gcc
  - clang

os:
  - linux

branches:
  only:
    - unit-tests

git:
  depth: 3

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CC=g++-4.9
        - CONFIG=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CC=g++-5
        - CONFIG=Release
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - CC=clang-3.6
        - CONFIG=Release
        - CONFIG=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - CC=clang-3.7
        - CONFIG=Release


before_install:
  - echo $PATH
  - if [ $TRAVIS_OS_NAME == linux ]; then . scripts/ci/before_install.sh; fi
  - echo $CC && echo ${CC} --version
  - echo $PATH

install:
  - mkdir build && cd build
  - echo $CONFIG
  - if [ "${CONFIG}" = "Debug" ]; then
        cmake -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TESTS=YES -DPERFORM_IO=NO -DIO_STATS=NO -DUSE_MPI=NO -DUSE_OPENMP=NO -DUSE_OPENACC=NO -DUSE_CUDA_KERNELS=NO ..
        ;
        make
        ;
    else
        cmake -DCMAKE_BUILD_TYPE=$CONFIG -DENABLE_TESTS=YES -DPERFORM_IO=NO -DIO_STATS=NO -DUSE_MPI=NO -DUSE_OPENMP=YES -DUSE_OPENACC=NO -DUSE_CUDA_KERNELS=NO ..
        ;
        make
        ;
    fi
  - cd -

before_script:
  - export OMP_NUM_THREADS=4

script:
  - . scripts/ci/run_tests.sh

after_success:
  - echo "Yess"

after_failure:
  - echo "Noooooooooooo <darth vader voice>"
